#!/usr/bin/env bash
# Generate Caddyfile for the kiosk LAN IP and run Caddy (HTTPS → Flask).
# Used by axon-attendance-caddy.service on the Vicharak kiosk.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CADDYFILE="${KIOSK_CADDYFILE:-$ROOT/Caddyfile}"
FLASK_URL="${KIOSK_FLASK_URL:-http://127.0.0.1:1337}"
HTTPS_PORT="${KIOSK_HTTPS_PORT:-8443}"
WAIT_FOR_FLASK=false

for arg in "$@"; do
  case "$arg" in
    --wait) WAIT_FOR_FLASK=true ;;
    --write-only)
      # Used by ExecStartPre: write Caddyfile then exit.
      WRITE_ONLY=true
      ;;
  esac
done
WRITE_ONLY="${WRITE_ONLY:-false}"

detect_lan_ip() {
  python3 -c "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.connect(('8.8.8.8', 80)); print(s.getsockname()[0])"
}

if ! command -v caddy >/dev/null; then
  echo "caddy not found on PATH. Install with scripts/install-kiosk-caddy.sh" >&2
  exit 1
fi

if ! curl -sf "${FLASK_URL}/" >/dev/null; then
  if "$WAIT_FOR_FLASK"; then
    echo "Waiting for Flask at ${FLASK_URL}..."
    until curl -sf "${FLASK_URL}/" >/dev/null; do
      sleep 1
    done
  else
    echo "Flask is not reachable at ${FLASK_URL}" >&2
    exit 1
  fi
fi

LAN_IP="$(detect_lan_ip)"
CA_CERT="${HOME}/.local/share/caddy/pki/authorities/local/root.crt"

cat >"$CADDYFILE" <<EOF
# Auto-generated by scripts/kiosk-caddy.sh — do not edit; restart Caddy to refresh LAN IP.
# Flask: ${FLASK_URL}  →  Caddy: https://${LAN_IP}:${HTTPS_PORT}

{
	local_certs
	# Non-root systemd unit cannot bind :80; phones hit :${HTTPS_PORT} directly.
	auto_https disable_redirects
	# Do not attempt sudo trust-store install under systemd (phones trust the CA manually).
	skip_install_trust
}

https://${LAN_IP}:${HTTPS_PORT}, https://localhost:${HTTPS_PORT}, https://127.0.0.1:${HTTPS_PORT} {
	bind 0.0.0.0
	bind [::]
	reverse_proxy 127.0.0.1:1337
	tls internal
}
EOF

echo "Wrote ${CADDYFILE} for LAN IP ${LAN_IP}"
echo "LAN HTTPS URL: https://${LAN_IP}:${HTTPS_PORT}"
echo "Trust CA (phones, one-time): ${CA_CERT}"

if "$WRITE_ONLY"; then
  exit 0
fi

exec caddy run --config "$CADDYFILE"
